[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#bbbbbb"
yellow = "#ebcb8b"

[colors.normal]
black = "#111111"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#bbbbbb"
yellow = "#ebcb8b"

[colors.primary]
background = "#111111"
foreground = "#bbbbbb"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "alacritty"

[font]
size = 9.5

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "bold_italic"

[font.italic]
family = "monospace"
style = "italic"

[font.normal]
family = "monospace"
style = "normal"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[window]
title = "Terminal"
